const copy = {
 en: {title:'Keep your terminals in context.', intro:'A spatial workspace for terminals, files and notes. Follow several tasks without losing the thread — in your browser or on your desktop.', eyebrow:'YOUR WORK, IN ONE WORKSPACE', features:'Workspace', desktop:'Desktop', docs:'Documentation', start:'Get started', source:'View source', dark:'Dark', light:'Light', alt:'gtmux canvas with three terminals, a release checklist and the Activity sidebar', caption:'A real demo workspace. Agent states are simulated through lifecycle hooks.', section:'A place for every task.', detail:'Arrange terminals alongside the files and notes that explain the work. Save the layout as a session and return with the context intact.', activity:'Know which terminal needs you.', activityText:'Activity brings working, completed and needs-input states into the sidebar. Connect agent lifecycle hooks for explicit status, and choose which indicators appear in your browser tab.', activityLink:'Explore agent integrations', control:'Your server. Your controls.', controlText:'Choose a workspace folder and port, then open the workspace in a browser, an app window, or both. Save settings with visible feedback and manage the server from one place.', controlLink:'Read the desktop guide', settings:'Settings that stay with your server.', settingsText:'Edit supported server settings in the UI and save them to TOML. Reload external changes, review validation errors and keep track of settings that require a restart.', access:'A clearer route to HTTPS.', accessText:'Set up a managed Caddy proxy for a domain or IP address, or connect your own proxy. The setup explains certificate choices and the network access you still need to provide.', accessLink:'Prepare external access', final:'Start with your own workspace.', finalText:'Run the server yourself or use a desktop package. Start with the installation guide for build instructions, package availability and platform requirements.', preview:'Development preview', previewText:'Linux and Windows flows have been tested locally. macOS and ARM runtime validation, signing and public release delivery remain release checks. Installers are available only when a repository publishes them.', footer:'A spatial workspace for terminal work.', setupAlt:'Desktop manager with workspace, port, access mode and saved setup feedback', activityAlt:'Activity settings with individual switches and browser title options', settingsAlt:'Server settings with validation and TOML controls', httpsAlt:'Managed HTTPS configuration for a domain'},
 ko: {title:'터미널과 작업 맥락을 한곳에.',intro:'터미널·파일·메모를 함께 배치하는 공간형 작업 환경. 브라우저와 데스크톱에서 여러 작업의 흐름을 이어가세요.',eyebrow:'나의 작업을 하나의 워크스페이스에',features:'워크스페이스',desktop:'데스크톱',docs:'문서',start:'시작하기',source:'소스 보기',dark:'다크',light:'라이트',alt:'터미널 세 개, 릴리스 체크리스트와 Activity 사이드바가 있는 gtmux 캔버스',caption:'실제 데모 워크스페이스입니다. 에이전트 상태는 수명 주기 훅으로 시뮬레이션했습니다.',section:'각 작업에 맞는 자리.',detail:'터미널 옆에 관련 파일과 메모를 배치하세요. 레이아웃을 세션으로 저장하고 작업 맥락을 그대로 이어갈 수 있습니다.',activity:'지금 확인할 터미널을 알아보세요.',activityText:'Activity 사이드바에서 작업 중·완료·입력 대기를 확인합니다. 에이전트 수명 주기 훅을 연결하면 명시적인 상태를 받고, 브라우저 탭에 표시할 항목도 고를 수 있습니다.',activityLink:'에이전트 연동 알아보기',control:'내 서버를 직접 관리하세요.',controlText:'워크스페이스 폴더와 포트를 고른 뒤 브라우저·앱 창·둘 다 중 원하는 방식으로 여세요. 설정 저장 결과를 확인하고 한곳에서 서버를 관리합니다.',controlLink:'데스크톱 가이드 읽기',settings:'서버와 함께 유지되는 설정.',settingsText:'지원하는 서버 설정을 UI에서 편집하고 TOML로 저장합니다. 외부 변경을 다시 불러오고, 검증 오류와 재시작이 필요한 설정을 확인하세요.',access:'HTTPS 설정을 더 쉽게.',accessText:'도메인이나 IP 주소에 관리형 Caddy 프록시를 설정하거나 기존 프록시를 연결하세요. 설정 화면과 가이드에서 인증서 선택과 별도로 준비할 네트워크 조건을 안내합니다.',accessLink:'외부 접속 준비하기',final:'나의 워크스페이스로 시작하세요.',finalText:'서버를 직접 실행하거나 데스크톱 패키지를 사용하세요. 설치 가이드에서 빌드 방법, 패키지 제공 여부와 플랫폼 요구사항을 확인할 수 있습니다.',preview:'개발 미리보기',previewText:'Linux와 Windows 흐름은 로컬에서 검증했습니다. macOS·ARM 실행 검증, 서명, 공개 릴리스 배포는 출시 전 확인이 남아 있습니다. 설치 파일은 저장소에서 배포한 경우에만 제공됩니다.',footer:'터미널 작업을 위한 공간형 워크스페이스.',setupAlt:'워크스페이스, 포트, 접속 방식과 저장 결과를 보여주는 데스크톱 관리자',activityAlt:'개별 스위치와 브라우저 탭 옵션이 있는 Activity 설정',settingsAlt:'설정 검증과 TOML 제어를 제공하는 서버 설정',httpsAlt:'도메인을 위한 관리형 HTTPS 설정'}
};
export function home(lang, base) {
 const t=copy[lang], other=lang==='en'?'ko':'en', doc=slug=>`${base}${lang}/${slug}.html`, shot=(name,alt,priority=false)=>`<img src="${base}assets/screenshots/${name}.png" alt="${alt}" ${priority?'fetchpriority="high"':'loading="lazy"'} width="${name.startsWith('manager')||name==='https-setup'?1180:1600}" height="${name.startsWith('manager')||name==='https-setup'?960:1040}">`;
 return `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${t.intro}"><title>gtmux — ${t.title}</title><link rel="icon" href="${base}assets/brand.png"><link rel="stylesheet" href="${base}assets/landing.css"></head><body>
<a class="skip" href="#main">${lang==='en'?'Skip to content':'본문으로 이동'}</a><header class="header"><a class="brand" href="${base}${lang}/home.html"><img src="${base}assets/brand.png" width="32" height="32" alt="">gtmux</a><nav aria-label="${lang==='en'?'Main navigation':'주 메뉴'}"><a href="#workspace">${t.features}</a><a href="#desktop">${t.desktop}</a><a href="${doc('index')}">${t.docs}</a><a href="${base}${other}/home.html" lang="${other}">${other==='ko'?'한국어':'English'}</a></nav></header>
<main id="main"><section class="hero"><div class="hero-copy"><p class="eyebrow">${t.eyebrow}</p><h1>${t.title}</h1><p class="lead">${t.intro}</p><div class="actions"><a class="button primary" href="${doc('install')}">${t.start}<span aria-hidden="true">↗</span></a><a class="text-link" href="https://github.com/iiamaii/gtmux">${t.source} <span aria-hidden="true">↗</span></a></div></div><figure class="hero-figure"><div class="figure-bar"><span>release-workspace</span><div role="group" aria-label="${lang==='en'?'Screenshot theme':'스크린샷 테마'}"><button type="button" data-theme="dark" aria-pressed="true">${t.dark}</button><button type="button" data-theme="light" aria-pressed="false">${t.light}</button></div></div><div id="workspace-preview">${shot('workspace-dark',t.alt,true)}</div><figcaption>${t.caption}</figcaption></figure></section>
<section id="workspace" class="section intro"><p class="eyebrow">01 / ${t.features}</p><h2>${t.section}</h2><p>${t.detail}</p></section>
<section class="section feature"><div><h2>${t.activity}</h2><p>${t.activityText}</p><a class="text-link" href="${doc('agents')}">${t.activityLink} →</a></div><figure>${shot('activity-settings',t.activityAlt)}</figure></section>
<section id="desktop" class="section feature reverse"><div><p class="eyebrow">02 / ${t.desktop}</p><h2>${t.control}</h2><p>${t.controlText}</p><a class="text-link" href="${doc('manager')}">${t.controlLink} →</a></div><figure>${shot('manager-saved',t.setupAlt)}</figure></section>
<section class="section feature"><div><h2>${t.settings}</h2><p>${t.settingsText}</p><a class="text-link" href="${doc('configuration-reference')}">${t.docs} →</a></div><figure>${shot('server-settings',t.settingsAlt)}</figure></section>
<section class="section feature reverse"><div><h2>${t.access}</h2><p>${t.accessText}</p><a class="text-link" href="${doc('external-access')}">${t.accessLink} →</a></div><figure>${shot('https-setup',t.httpsAlt)}</figure></section>
<section class="section get-started"><div><p class="eyebrow">03 / ${t.start}</p><h2>${t.final}</h2><p>${t.finalText}</p><a class="button primary" href="${doc('install')}">${t.start} ↗</a></div><aside><h3>${t.preview}</h3><p>${t.previewText}</p></aside></section></main><footer><a class="brand" href="${base}${lang}/home.html">gtmux</a><span>${t.footer}</span><a href="https://github.com/iiamaii/gtmux">GitHub ↗</a></footer><script type="module" src="${base}assets/landing.js"></script></body></html>`;
}
